/**
 * Content plan: the brand's publishing calendar. "Topic for a date" slots are
 * generated by an LLM (plan/generate: ideas from the model, dates deterministically
 * from perWeek), edited manually (drag between days, custom topics), and launched
 * into an article with one action (write → startRun, the slot gets a run_id and
 * then shows the run's live status). Isolation works like runs: a slot belongs to a
 * brand, ownership is checked in assertRunAccess (404 for someone else's).
 */
import {
  BadRequestException,
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  Param,
  Patch,
  Post,
  Query,
  Req,
  ServiceUnavailableException,
  UseGuards,
} from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import type { Request } from 'express';
import { PlanGuard } from '../../auth/plan.guard';
import { LlmRateGuard } from '../llm-rate.guard';
import { BlogBrandContext } from '../brand-context';
import { PostQuotaService } from '../post-quota';
import { resolveSettings } from '../server/utils/appSettings';
import { LLM } from '../server/utils/llm';
import { generatePlanIdeas, parseDay, planSlots, type PlanIdea } from '../server/utils/pipeline/plan';
import { startRun } from '../server/utils/pipeline/run';
import {
  clearPlannedItems,
  createPlanItems,
  deletePlanItem,
  getPlanItem,
  getRunRow,
  listPlanItems,
  listRunBriefs,
  listRunSchedules,
  updatePlanItem,
  type PlanItemRow,
  type RunBrief,
} from '../server/utils/store';
import { parseSchedule } from '../server/utils/publishSchedule';

const MAX_RANGE_DAYS = 92; // generate the plan for at most a quarter at a time
const ITEM_STATUSES = new Set(['planned', 'skipped']);
const TIME_RE = /^([01]\d|2[0-3]):[0-5]\d$/; // 'HH:mm' 24h

/** '' → no time (all day); 'HH:mm' gets validated; otherwise 400. */
const normTime = (raw: unknown): string => {
  const t = String(raw ?? '').trim();
  if (!t) return '';
  if (!TIME_RE.test(t)) throw new BadRequestException('time must be in HH:mm format');
  return t;
};

const parseQueries = (raw: string): string[] => {
  try {
    const arr = JSON.parse(raw || '[]');
    return Array.isArray(arr) ? arr.map(String) : [];
  } catch {
    return [];
  }
};

/** DB row → API response (queries unpacked, run status attached). */
const toApiItem = (row: PlanItemRow, run?: RunBrief) => ({
  id: row.id,
  date: row.date,
  time: row.time || '',
  title: row.title,
  angle: row.angle,
  intent: row.intent,
  keyword: row.keyword,
  queries: parseQueries(row.queries_json),
  category: row.category,
  status: row.status,
  score: row.score,
  runId: run ? row.run_id : '', // run was deleted → slot is free again
  run: run
    ? { status: run.status, title: run.title, blogStatus: run.blog_status, blogSlug: run.blog_slug, coverUrl: run.cover_url, wordCount: run.word_count }
    : null,
});

/** Auto-posting schedule entry in the calendar response (flat, with the article's title). */
interface ScheduleCell {
  runId: string;
  runTitle: string;
  entryId: string;
  channel: string;
  at: string;
  status: string;
  error?: string;
}

/**
 * Schedules of all the brand's articles that fall within from..to. One query for runs
 * with a non-empty publish_schedule_json (no article bodies) — splitting into slots
 * with separate queries isn't an option, that's N+1 for every calendar month.
 *
 * Boundaries are compared by calendar day UTC: from/to arrive as YYYY-MM-DD,
 * and a slot on "the 12th" must fall within a period that ends on the 12th.
 */
async function brandSchedule(brandId: number, from?: string, to?: string): Promise<ScheduleCell[]> {
  const rows = await listRunSchedules(brandId);
  const out: ScheduleCell[] = [];
  for (const row of rows) {
    for (const e of parseSchedule(row.publish_schedule_json)) {
      const day = e.at.slice(0, 10);
      if (from && day < from) continue;
      if (to && day > to) continue;
      out.push({
        runId: row.id,
        runTitle: row.title || row.topic || '',
        entryId: e.id,
        channel: e.channel,
        at: e.at,
        status: e.status,
        ...(e.error ? { error: e.error } : {}),
      });
    }
  }
  return out.sort((a, b) => (a.at < b.at ? -1 : a.at > b.at ? 1 : 0));
}

@Controller('blogwriter')
@UseGuards(PlanGuard)
export class PlanController {
  constructor(
    private readonly brandCtx: BlogBrandContext,
    private readonly quota: PostQuotaService,
  ) {}

  /**
   * Access to a slot for MUTATION (edit/delete/launch): owner/editor of the slot's
   * brand or an admin; viewer → 403; someone else's → 404 (same as runs). All callers
   * of this helper are mutations.
   */
  private async itemOr404(req: Request, id: string): Promise<PlanItemRow> {
    const item = await getPlanItem(String(id));
    await this.brandCtx.assertRunMutate(req, item ?? null);
    return item as PlanItemRow;
  }

  private validRange(from?: string, to?: string): { from: string; to: string } {
    const start = parseDay(String(from ?? ''));
    const end = parseDay(String(to ?? ''));
    if (!start || !end) throw new BadRequestException('from and to dates are required in YYYY-MM-DD format');
    if (start > end) throw new BadRequestException('from is after to');
    if ((end.getTime() - start.getTime()) / 86_400_000 > MAX_RANGE_DAYS) {
      throw new BadRequestException(`period must not exceed ${MAX_RANGE_DAYS} days`);
    }
    return { from: String(from), to: String(to) };
  }

  /**
   * The active brand's plan slots within the date range + live statuses of launched
   * articles + auto-posting schedule (schedule): the calendar shows not just
   * "when to write" but also "when and where the article will go on its own".
   */
  @Get('plan')
  async list(@Req() req: Request, @Query('from') from?: string, @Query('to') to?: string) {
    const brandId = await this.brandCtx.brandId(req);
    if (!brandId && !this.brandCtx.isAdmin(req)) return { items: [], schedule: [], brand: '', mock: false };
    if (from || to) this.validRange(from || to, to || from); // validate the format, the range itself is optional
    const items = await listPlanItems(brandId, from, to);
    const runs = await listRunBriefs(items.map((i) => i.run_id).filter(Boolean));
    const byId = new Map(runs.map((r) => [r.id, r]));
    const s = await resolveSettings(brandId);
    return {
      items: items.map((i) => toApiItem(i, byId.get(i.run_id))),
      schedule: await brandSchedule(brandId, from, to),
      brand: s.brand,
      mock: new LLM(s).isMock,
    };
  }

  /**
   * Generate a plan for a period: dates — planSlots(from,to,perWeek), topics — LLM.
   * append=true fills in free days; otherwise planned slots in the period without an
   * article are replaced (slots with launched articles are untouched). Mock output isn't saved.
   */
  @Post('plan/generate')
  @UseGuards(LlmRateGuard)
  @HttpCode(200)
  async generate(
    @Req() req: Request,
    @Body() body: { from?: string; to?: string; perWeek?: number; seed?: string; append?: boolean },
  ) {
    const brandId = await this.brandCtx.brandId(req);
    if (!brandId && !this.brandCtx.isAdmin(req)) {
      throw new BadRequestException('Create a brand in onboarding first — the plan is tied to a brand');
    }
    await this.brandCtx.assertBrandMutate(req); // viewer can't generate a plan
    const { from, to } = this.validRange(body?.from, body?.to);
    const perWeek = Math.min(Math.max(Number(body?.perWeek) || 3, 1), 7);

    if (!body?.append) await clearPlannedItems(brandId, from, to);

    // free dates in the period: the perWeek pattern minus days already taken by slots
    const existing = await listPlanItems(brandId, from, to);
    const busy = new Set(existing.map((i) => i.date));
    const freeSlots = planSlots(from, to, perWeek).filter((d) => !busy.has(d));

    const s = await resolveSettings(brandId);
    const llm = new LLM(s);
    let created: PlanIdea[] = [];
    if (freeSlots.length) {
      // avoid repeating both the period's taken topics and the rest of the brand's plan
      const avoid = (await listPlanItems(brandId)).map((i) => i.title);
      try {
        created = await generatePlanIdeas(String(body?.seed ?? ''), freeSlots.length, llm, s, avoid);
      } catch (e: any) {
        // surface the provider failure reason to the user: "generated 0" with no
        // explanation looked like a broken button (real case: kie 500 + OpenRouter
        // "empty response" on the same model at the same time)
        const reason = String(e?.message || e || '').slice(0, 300);
        throw new ServiceUnavailableException(
          `The model didn't respond${reason ? `: ${reason}` : ''} — try again or switch models in the "Agent profile"`,
        );
      }
      if (!created.length && !llm.isMock) {
        throw new ServiceUnavailableException(
          'The model returned no ideas — try again or switch models in the "Agent profile"',
        );
      }
      if (created.length && !llm.isMock) {
        await createPlanItems(created.map((idea, i) => ({
          id: randomUUID(),
          brandId,
          date: freeSlots[i],
          time: '',
          title: idea.title,
          angle: idea.angle,
          intent: idea.intent,
          keyword: idea.keyword,
          queries_json: JSON.stringify(idea.queries),
          category: idea.category,
          status: 'planned',
          run_id: '',
          score: idea.score,
        })));
      }
    }

    if (llm.isMock) {
      // don't write mock output to the DB (same as topics/ideas) — return it ephemerally to preview the UI
      const now = new Date().toISOString();
      const mockItems = created.map((idea, i) => ({
        ...toApiItem({
          id: `mock-${i}`, brandId, date: freeSlots[i] ?? from, time: '', title: idea.title, angle: idea.angle,
          intent: idea.intent, keyword: idea.keyword, queries_json: JSON.stringify(idea.queries),
          category: idea.category, status: 'planned', run_id: '', score: idea.score, created_at: now, updated_at: now,
        }),
      }));
      return { items: mockItems, generated: mockItems.length, brand: s.brand, mock: true };
    }

    const items = await listPlanItems(brandId, from, to);
    const runs = await listRunBriefs(items.map((i) => i.run_id).filter(Boolean));
    const byId = new Map(runs.map((r) => [r.id, r]));
    return {
      items: items.map((i) => toApiItem(i, byId.get(i.run_id))),
      generated: created.length,
      brand: s.brand,
      mock: false,
    };
  }

  /** Add a slot manually: { date, title, ... } → slot. */
  @Post('plan/items')
  @HttpCode(200)
  async create(
    @Req() req: Request,
    @Body() body: { date?: string; time?: string; title?: string; angle?: string; intent?: string; keyword?: string; queries?: string[]; category?: string },
  ) {
    const brandId = await this.brandCtx.brandId(req);
    if (!brandId && !this.brandCtx.isAdmin(req)) {
      throw new BadRequestException('Create a brand in onboarding first — the plan is tied to a brand');
    }
    await this.brandCtx.assertBrandMutate(req); // viewer can't add slots
    const title = String(body?.title ?? '').trim();
    if (!title) throw new BadRequestException('title is required');
    if (!parseDay(String(body?.date ?? ''))) throw new BadRequestException('date must be in YYYY-MM-DD format');
    const time = normTime(body?.time);
    const queries = (Array.isArray(body?.queries) ? body.queries : [])
      .map(String).map((q) => q.trim()).filter(Boolean).slice(0, 4);
    const id = randomUUID();
    await createPlanItems([{
      id,
      brandId,
      date: String(body!.date),
      time,
      title,
      angle: String(body?.angle ?? '').trim(),
      intent: String(body?.intent ?? 'informational'),
      keyword: String(body?.keyword ?? '').trim(),
      queries_json: JSON.stringify(queries),
      category: String(body?.category ?? '').trim(),
      status: 'planned',
      run_id: '',
      score: 0,
    }]);
    const item = await getPlanItem(id);
    return { item: toApiItem(item as PlanItemRow) };
  }

  /** Edit a slot: move date (dnd), title, category, status planned|skipped. */
  @Patch('plan/items/:id')
  async update(
    @Req() req: Request,
    @Param('id') id: string,
    @Body() body: { date?: string; time?: string; title?: string; angle?: string; keyword?: string; queries?: string[]; category?: string; status?: string },
  ) {
    const item = await this.itemOr404(req, id);
    const fields: Partial<PlanItemRow> = {};
    if (body?.date !== undefined) {
      if (!parseDay(String(body.date))) throw new BadRequestException('date must be in YYYY-MM-DD format');
      fields.date = String(body.date);
    }
    if (body?.time !== undefined) fields.time = normTime(body.time);
    if (body?.title !== undefined) {
      const t = String(body.title).trim();
      if (!t) throw new BadRequestException('title cannot be empty');
      fields.title = t;
    }
    if (body?.angle !== undefined) fields.angle = String(body.angle).trim();
    if (body?.keyword !== undefined) fields.keyword = String(body.keyword).trim();
    if (body?.category !== undefined) fields.category = String(body.category).trim();
    if (body?.queries !== undefined) {
      const queries = (Array.isArray(body.queries) ? body.queries : [])
        .map(String).map((q) => q.trim()).filter(Boolean).slice(0, 4);
      fields.queries_json = JSON.stringify(queries);
    }
    if (body?.status !== undefined) {
      if (!ITEM_STATUSES.has(String(body.status))) throw new BadRequestException('status: planned | skipped');
      fields.status = String(body.status);
    }
    await updatePlanItem(item.id, fields);
    const fresh = await getPlanItem(item.id);
    const run = fresh?.run_id ? (await listRunBriefs([fresh.run_id]))[0] : undefined;
    return { item: toApiItem(fresh as PlanItemRow, run) };
  }

  @Delete('plan/items/:id')
  async remove(@Req() req: Request, @Param('id') id: string) {
    const item = await this.itemOr404(req, id);
    await deletePlanItem(item.id);
    return { ok: true };
  }

  /** Launch an article from a slot: startRun for the slot's topic with its AEO queries → { runId }. */
  @Post('plan/items/:id/write')
  @HttpCode(200)
  async write(@Req() req: Request, @Param('id') id: string, @Body() body: { mode?: string }) {
    const item = await this.itemOr404(req, id);
    // already launched and the run is alive — don't spawn a duplicate, route to it (no quota spent)
    if (item.run_id && (await getRunRow(item.run_id))) return { runId: item.run_id };
    // daily post quota — per OWNER of the slot's brand (admin — no limit)
    await this.quota.assertCanStart(req, item.brandId || undefined);
    const mode = body?.mode === 'auto' ? 'auto' : 'interactive';
    const runId = await startRun(item.title, parseQueries(item.queries_json), mode, item.brandId || null);
    await updatePlanItem(item.id, { run_id: runId, status: 'planned' });
    return { runId };
  }
}
