/**
 * Storage for article body media (blog_media) — images, video, audio, files
 * inserted into the text via the editor.
 *
 * Why in the DB and not only on disk: links like /blogwriter/media/<file> live
 * inside the published HTML, meaning they must survive both deploys and server
 * moves — while data/ on the worker survives neither. Disk remains a serving
 * cache (see covers.controller: disk → fallback to DB → file restoration).
 *
 * Like previewStore, all functions tolerate the table being absent (deploy
 * ahead of the migration): reads return empty, writes are silently skipped —
 * the file still landed on disk, so the editor doesn't break.
 */
import { blogPrisma } from './prisma'

export type MediaKind = 'image' | 'video' | 'audio' | 'file'

/** A media row with bytes — for serving. */
export interface StoredMedia {
  id: number
  kind: MediaKind
  mime: string
  /** null if only metadata was requested (withBytes=false) */
  bytes: Buffer | null
  sizeBytes: number
  fileName: string
  origName: string
}

/** A media row without bytes — for the article library. */
export interface MediaItem {
  id: number
  kind: MediaKind
  mime: string
  name: string
  size: number
  width: number | null
  height: number | null
  fileName: string
  createdAt: string
}

export interface SaveMediaInput {
  userId?: number | null
  brandId?: number | null
  runId?: string | null
  kind: MediaKind
  mime: string
  bytes: Buffer
  /** name in the public URL — unique, generated by the controller */
  fileName: string
  origName?: string | null
  width?: number | null
  height?: number | null
}

const KINDS: ReadonlySet<string> = new Set(['image', 'video', 'audio', 'file'])

function toKind(v: unknown): MediaKind {
  const s = String(v ?? '')
  return (KINDS.has(s) ? s : 'file') as MediaKind
}

function toIso(v: unknown): string {
  return v instanceof Date ? v.toISOString() : String(v ?? '')
}

/** Save a file. Returns the row id, or null if the table doesn't exist yet. */
export async function saveMedia(input: SaveMediaInput): Promise<number | null> {
  try {
    const rows = await blogPrisma().$queryRawUnsafe<{ id: bigint }[]>(
      `INSERT INTO blog_media
         (user_id, brand_id, run_id, kind, mime, bytes, size_bytes, file_name, orig_name, width, height)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
       ON CONFLICT (file_name)
         DO UPDATE SET bytes = EXCLUDED.bytes, size_bytes = EXCLUDED.size_bytes, created_at = now()
       RETURNING id`,
      input.userId ?? null,
      input.brandId ?? null,
      input.runId ?? null,
      input.kind,
      input.mime,
      input.bytes,
      input.bytes.length,
      input.fileName,
      (input.origName ?? '').slice(0, 300),
      input.width ?? null,
      input.height ?? null,
    )
    return rows?.[0]?.id != null ? Number(rows[0].id) : null
  } catch {
    return null
  }
}

/**
 * Media by file name from the public URL. withBytes=false — metadata only:
 * on a disk cache hit there's no point pulling the bytea (up to 100 MB), but
 * the mime type and original name are still needed for Content-Disposition.
 */
export async function getMediaByFile(file: string, withBytes = true): Promise<StoredMedia | null> {
  if (!file) return null
  try {
    const cols = withBytes
      ? 'id, kind, mime, bytes, size_bytes, file_name, orig_name'
      : 'id, kind, mime, NULL::bytea AS bytes, size_bytes, file_name, orig_name'
    const rows = await blogPrisma().$queryRawUnsafe<any[]>(
      `SELECT ${cols} FROM blog_media WHERE file_name = $1`, file)
    const r = rows?.[0]
    if (!r) return null
    return {
      id: Number(r.id),
      kind: toKind(r.kind),
      mime: r.mime || 'application/octet-stream',
      bytes: r.bytes ?? null,
      sizeBytes: Number(r.size_bytes || 0),
      fileName: r.file_name,
      origName: r.orig_name || '',
    }
  } catch {
    return null
  }
}

/** Media by id (for deletion/internal scenarios). */
export async function getMediaById(id: number, withBytes = false): Promise<StoredMedia | null> {
  if (!Number.isFinite(id) || id <= 0) return null
  try {
    const cols = withBytes
      ? 'id, kind, mime, bytes, size_bytes, file_name, orig_name'
      : 'id, kind, mime, NULL::bytea AS bytes, size_bytes, file_name, orig_name'
    const rows = await blogPrisma().$queryRawUnsafe<any[]>(
      `SELECT ${cols} FROM blog_media WHERE id = $1`, id)
    const r = rows?.[0]
    if (!r) return null
    return {
      id: Number(r.id),
      kind: toKind(r.kind),
      mime: r.mime || 'application/octet-stream',
      bytes: r.bytes ?? null,
      sizeBytes: Number(r.size_bytes || 0),
      fileName: r.file_name,
      origName: r.orig_name || '',
    }
  } catch {
    return null
  }
}

/** Article media library: newest first, no bytes. */
export async function listRunMedia(runId: string, limit = 200): Promise<MediaItem[]> {
  if (!runId) return []
  try {
    const rows = await blogPrisma().$queryRawUnsafe<any[]>(
      `SELECT id, kind, mime, size_bytes, file_name, orig_name, width, height, created_at
         FROM blog_media
        WHERE run_id = $1
        ORDER BY created_at DESC
        LIMIT $2`,
      runId, Math.min(Math.max(1, limit), 200))
    return (rows || []).map((r) => ({
      id: Number(r.id),
      kind: toKind(r.kind),
      mime: r.mime || 'application/octet-stream',
      name: r.orig_name || r.file_name,
      size: Number(r.size_bytes || 0),
      width: r.width == null ? null : Number(r.width),
      height: r.height == null ? null : Number(r.height),
      fileName: r.file_name,
      createdAt: toIso(r.created_at),
    }))
  } catch {
    return []
  }
}

/** What the file is attached to — used by the caller to check permissions (see media.controller). */
export interface MediaOwner {
  id: number
  runId: string | null
  brandId: number | null
  userId: number | null
  fileName: string
}

export async function getMediaOwner(id: number): Promise<MediaOwner | null> {
  if (!Number.isFinite(id) || id <= 0) return null
  try {
    const rows = await blogPrisma().$queryRawUnsafe<any[]>(
      'SELECT id, run_id, brand_id, user_id, file_name FROM blog_media WHERE id = $1', id)
    const r = rows?.[0]
    if (!r) return null
    return {
      id: Number(r.id),
      runId: r.run_id ?? null,
      brandId: r.brand_id == null ? null : Number(r.brand_id),
      userId: r.user_id == null ? null : Number(r.user_id),
      fileName: r.file_name,
    }
  } catch {
    return null
  }
}

/**
 * Delete media from the library. Scope is the BRAND, not the uploading user:
 * media belongs to the brand's article, and an editor invited into someone
 * else's workspace must be able to remove a colleague's image (the condition
 * used to be `user_id = mine`, and a file in a shared article couldn't be
 * deleted by anyone but the uploader). Permissions are checked by the caller
 * (assertRunMutate on the run); the condition here is a second line of defense
 * against id guessing. Rows without brand_id (legacy, predating the column)
 * remain on the "own it" rule. Returns the file name (for cleaning up the
 * disk cache), or null.
 */
export async function deleteMedia(id: number, scope: { brandId?: number | null; userId?: number | null }): Promise<string | null> {
  if (!Number.isFinite(id) || id <= 0) return null
  const brandId = scope.brandId ?? 0
  const userId = scope.userId ?? 0
  if (brandId <= 0 && userId <= 0) return null
  try {
    const rows = brandId > 0
      ? await blogPrisma().$queryRawUnsafe<{ file_name: string }[]>(
        'DELETE FROM blog_media WHERE id = $1 AND brand_id = $2 RETURNING file_name', id, brandId)
      : await blogPrisma().$queryRawUnsafe<{ file_name: string }[]>(
        'DELETE FROM blog_media WHERE id = $1 AND user_id = $2 RETURNING file_name', id, userId)
    return rows?.[0]?.file_name ?? null
  } catch {
    return null
  }
}
